### ISSUE TITLE
[BORK] Spawn RTP spam

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#100]
> **Describe the bug**:
The message fires _every_ time you leave spawn

> **How To Reproduce**:

leave spawn

> **Expected behavior**:
Shouldnt happen more than once

> **Screenshots**:

![image](https://user-images.githubusercontent.com/25861695/93192144-31717f00-f6fa-11ea-9217-cd2a659ba7ea.png)

**Comment by Ph4i1ur3** [comment]
Resolved by #103
