### ISSUE TITLE
[BORK] Unparsed tag on Claims Shop

### ISSUE THREAD

**Issue by Mutim** [Adriftus-Studios/network-script-data#107]
1. Go to Claims Shop in marketplace
2. Click on the shop person thing
3. Hover over "Upgrade Claim Limit

![image](https://user-images.githubusercontent.com/22847483/93381511-64b12c80-f826-11ea-9cc3-dd35d04e0b68.png)

**Comment by BehrRiley** [comment]
Pull request [`[#111]`](https://github.com/BehrRiley/network-script-data/pull/111) touched on a consistency update for this script, but the actual issue is likely caused from the script trying to parse player based tags within the `procedural items` section of the script

**Comment by Ph4i1ur3** [comment]
Fixed by #131 and #133
