### ISSUE TITLE
Diamond swords 

### ISSUE THREAD

**Issue by Yesboy77** [Adriftus-Studios/network-script-data#117]
Diamond sword have thebase damage and level stars showing nothing. I crafted 2 diamond swords and enchanted one of them. The enchanted sword had the glow as if it had an enchantment, but didn't say what the enchantment is.

![20201009_233129](https://user-images.githubusercontent.com/72634304/95644878-d11af680-0a87-11eb-9d00-6995a86664a1.jpg)

![20201009_233121](https://user-images.githubusercontent.com/72634304/95644883-d4ae7d80-0a87-11eb-8302-b25871baf0f9.jpg)

**Comment by BehrRiley** [comment]
It appears this was borked from an invalid reference for the item's damage; I've corrected the reference and this should be resolved now
