### ISSUE TITLE
[BORKED] parkour_quit_command error on Survival

### ISSUE THREAD

**Issue by BehrRiley** [Adriftus-Studios/network-script-data#121]
> **Error Message**:

`'parkour_complete' is an unknown argument! Did you forget quotes, or did you mess up the command syntax?`

> **Script Information**:

Script Name:  `parkour_quit_command`

Script Reference:  [`survival/./repo_link/spawn_scripts/spawn_parkour.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/spawn_scripts/spawn_parkour.dsc#L67)

Script Line: `67`

> **Player Attached**:

`Eutherin` / `(47951ae6-aab4-4f72-a40f-fae9003e1785`

This error is the result of the teleport command failing to utilize `parkour_complete` as a valid location; `<location[parkour_complete]>` is invalid, so it's likely this noted location just needs created.

**Comment by Eutherin** [comment]
Resolved as part of updates.
