### ISSUE TITLE
[BORKED] Claim scripts error on Survival

### ISSUE THREAD

**Issue by BehrRiley** [Adriftus-Studios/network-script-data#122]
> **Error Messages**:

`Tag-base 'read' returned null.`

> **Script Information**:

Script Names:  

- `claim_system_upgrade_spawn_prevention`
- `claiming_system_upgrade_events`
- `claiming_system_bossbar_start`

Script References:  
- [`survival/./repo_link/global_systems/chunk_claim_protection.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/global_systems/chunk_claim_protection.dsc#L1423) - Script Line: `1423`
- [`survival/./repo_link/global_systems/chunk_claim_protection.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/global_systems/chunk_claim_protection.dsc#L1267) - Script Line: `1267`
- [`survival/./repo_link/global_systems/chunk_claim_protection.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/global_systems/chunk_claim_protection.dsc#L1302) - Script Line: `1302`

Script error occurs: `10553` times per hour when relevant.

> **Quick summary**:

Unsure of any causes here; the entire script is verbose, has scripts that are not even in use, and is very long. research needs done.

**Comment by Eutherin** [comment]
@Ph4i1ur3

**Comment by Ph4i1ur3** [comment]
should be fixed. Re-report if not.
