### ISSUE TITLE
[BORKED]gamemode_handle_command error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#125]
> **Error Message**:

`Tag <[target].is_player> is invalid!`

> **Script Information**:

Script Name:  `gamemode_handle_command`

Script Reference:  [`survival/./repo_link/Commands/gamemode.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/Commands/gamemode.dsc#L77)

Script Line: 77

> **Player Attached**:

`Mutim_Endymion` / `(820accf7-c943-40ff-beb2-961533406efa`

**Comment by Ph4i1ur3** [comment]
https://github.com/Adriftus-Studios/network-script-data/blob/1aabeae2ae4880b5a439efcc2349c1ac6b6df0e7/denizen_scripts/survival/repo_link/Commands/gamemode.dsc#L74
Need to properly instantiate the list here.
Low priority due to being an admin command.

**Comment by Ph4i1ur3** [comment]
Fixed in #131
