### ISSUE TITLE
[BORKED]claim_system_build_chunkmap error on Survival   GENERATES SEVERE LAG BEFORE OPENING GUI

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#127]
> **Error Message**:

`Tag-base 'read' returned null.`

> **Script Information**:

Script Name:  `claim_system_build_chunkmap`

Script Reference:  [`survival/./repo_link/global_systems/chunk_claim_protection.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/global_systems/chunk_claim_protection.dsc#L1548)

Script Line: 1548

> **Player Attached**:

`Eutherin` / `(47951ae6-aab4-4f72-a40f-fae9003e1785`

**Comment by Ph4i1ur3** [comment]
Should be fixed.
