### ISSUE TITLE
[BORKED]store_hub_cosmeticshop_titles_events error on Survival  ALSO GIVES PLAYERS NAMETAGS

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#128]
> **Error Message**:

`Missing script for procedure script tag 'getGlobalPlayerData'!`

> **Script Information**:

Script Name:  `store_hub_cosmeticshop_titles_events`

Script Reference:  [`survival/./repo_link/shops/Cosmetics_Shop.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/shops/Cosmetics_Shop.dsc#L98)

Script Line: 98

> **Player Attached**:

`Eutherin` / `(47951ae6-aab4-4f72-a40f-fae9003e1785`

Please note buying a title you dont already have is currently giving the title, AND the voucher item

**Comment by BehrRiley** [comment]
The primary issue here is that `getGlobalPlayerData` is not a valid script at all on the network and I can't determine what it was previously to restore it, it dates before the repository setup date after reviewing the repository's history.

**Comment by Ph4i1ur3** [comment]
Fixed in PR
