### ISSUE TITLE
[Enhancement] Stonks shop noisy af

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#129]
> **Describe the bug**:

Shift double clicking the glass is loud as heck in the stonks window, and clicking ANYWHERE makes the noise also.

> **Screenshots**:
https://youtu.be/efX_pu2ynYU
https://youtu.be/J8NRJF08ews

> **Additional context**:

**Comment by BehrRiley** [comment]
I personally use `volume:0.25` when using volume on GUIs, we may try that out, it's comfortably subtle

**Comment by Eutherin** [comment]
we should remove it from this shop or add it to the others. its the only survival shop that makes any noise
