### ISSUE TITLE
Mystery vendor rework.

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#13]
> **The Type of request**:
Rework.

> **Who is requesting this**:
Eutherin.

> **Describe the feature**:
Needs to be reworked to use new tokens, have rewards implemented, etc.

> **Describe the impact**: 
Currently the mystery vendor doesn't provide anything.

> **Describe the cost of not doing this request**: 
Spawn looks janky af with vendors that don't work.

> **Describe if you have any ideas on how we may solve this**: 
Random things like backpacks/etc, materials, blocks, souls, cosmetics and titles could all be in there.

> **Describe how urgent this is and why**: 
Need it to get spawn up to par for survival.

**Comment by pjochillin** [comment]
Also, when trying to buy items from the Mystery Vendor, it borks in chat (see attached screenshot)
![image](https://user-images.githubusercontent.com/30186714/89714344-cea6fe00-d96b-11ea-9e14-0ce2a0953d4b.png)

**Comment by pjochillin** [comment]
The above bork should be fixed in my latest pull request (14).
