### ISSUE TITLE
[BORK] Mystery vendor doesnt give boxes or take money

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#130]
> **Describe the bug**:

See title

> **How To Reproduce**:

Example:
go to mystery vendor
buy this box
![image](https://user-images.githubusercontent.com/25861695/97077733-f4bb6200-159a-11eb-881a-c4c98f17cd8a.png)

> **Expected behavior**:

Take my money, give me mystery box

> **Screenshots**:

![image](https://user-images.githubusercontent.com/25861695/97077724-e8370980-159a-11eb-866e-53f17b63f705.png)

![image](https://user-images.githubusercontent.com/25861695/97077729-ebca9080-159a-11eb-9c76-ddf0aeeefaa7.png)

> **Additional context**:

**Comment by Eutherin** [comment]
for the record, i can afford those boxes.
![image](https://user-images.githubusercontent.com/25861695/97077750-0ac92280-159b-11eb-82ec-e4b237eae4b9.png)

**Comment by BehrRiley** [comment]
Here's a reference of the relevant script:

https://github.com/Adriftus-Studios/network-script-data/blob/fe12014df27cdf626315732da50189ad63da4f1b/denizen_scripts/survival/repo_link/shops/Mystery_Shop.dsc#L92

**Comment by BehrRiley** [comment]
it looks like we validate currency with `<player.money> >= <context.item.nbt[price]>` but the only command utilized that looks economic is `- yaml id:global.player.<player.uuid> set Economy.AdriftusCoin:-:<context.item.nbt[price]>` which uh, doesn't look like it's the same value of currency if this is adjusting an economy script value

**Comment by Ph4i1ur3** [comment]
We need to re-add GadgetsMenu and implement premium currency (the latter will likely be week 1 update)
