### ISSUE TITLE
Border script cleanup - Xeane

### ISSUE THREAD

**Issue by Grumblin** [Adriftus-Studios/network-script-data#134]
Clean up current borders
Add the rest of the borders
Showfake the border to be a world border
border take down (see your list of resources/tasks)

**Comment by BehrRiley** [comment]
What does it mean to clean up current borders?

**Comment by Eutherin** [comment]
@Grumblin 
See above

**Comment by Eutherin** [comment]
Closing as it's not really necessary to keep open as an issue. no sense in automating it as a script when its a 5 second command.
