### ISSUE TITLE
RTP Command

### ISSUE THREAD

**Issue by Indestructoyed** [Adriftus-Studios/network-script-data#143]
Need a command for RTP because having to go back to spawn and jump is just too much

**Comment by Eutherin** [comment]
Or a ratelimit on how often they can yeet themselves off spawn to avoid abuse of that.

**Comment by Eutherin** [comment]
For example we had Taras hunting for villages a good portion of the night to steal bookshelves.

**Comment by BehrRiley** [comment]
The push for minimizing commands was primarily an attempt to sustain integrity around a game-mode that relied less on "magic teleport commands" - where a player would type a command and you would whoosh away at any given moment. This is why we've moved `tpa`/`tpahere` type command requests into "teleport stones" in a future update. 

We could probably stick the same concept of RTP teleportation into something like that as well.

**Comment by Eutherin** [comment]
Do we have a way to ratelimit how often players go to spawn?

**Comment by BehrRiley** [comment]
could teleport them someplace else like the spawn or something, or let them actually die trying to abuse the system

**Comment by Eutherin** [comment]
#fuck the players?

Attempted to address on upcoming pr:
https://github.com/BehrRiley/network-script-data/pull/120/
