### ISSUE TITLE
[BORKED]warp_management_gui_panel_populate error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#144]
> **Error Message**:

`Tag-base 'item' returned null.`

> **Script Information**:

Script Name:  `warp_management_gui_panel_populate`

Script Reference:  [`survival/./repo_link/global_systems/warps.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/global_systems/warps.dsc#L489)

Script Line: 489

> **Player Attached**:

`GavinPlayzMC` / `(f2d5fafe-3900-46c9-946b-81475553f6c7`

**Comment by BehrRiley** [comment]
This is a duplicate to the issue I saw and commented on before this one here: #147
