### ISSUE TITLE
[BORKED]backpack_save error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#145]
> **Error Message**:

`Cannot apply NBT to AIR!`

> **Script Information**:

Script Name:  `backpack_save`

Script Reference:  [`survival/./repo_link/items/backpack.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/items/backpack.dsc#L135)

Script Line: 135

> **Player Attached**:

`smurphy1996` / `(8f06bba3-d40f-44e3-92b1-f14318ed6581`

**Comment by BehrRiley** [comment]
this is likely the result of assuming the player's held slot is still the backpack, or the player managing to move it from the slot they had it in originally

**Comment by Eutherin** [comment]
Seems to have been resolved.
