### ISSUE TITLE
Mute staff teleportation messages.

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#148]
> **The Type of request**:

See title
> **Who is requesting this**:

Eutherin

> **Describe the feature**:

a staff member in spectate mode teleporting to someone shouldnt trigger chat messages

> **Describe the impact**: 

Makes it easier to catch cheaters.

> **Describe the reach of this feature**:

Admin crap

> **Describe the cost of not doing this request**: 

Doing check of players for xray/hax
player gets message saying hurduryourebeingwatched

> **Describe which goals this helps**: 

rules enforcement

> **Describe the evidence that you have on the need for this request**: 

![image](https://user-images.githubusercontent.com/25861695/97103092-ab851400-1667-11eb-811c-7c86c2a47260.png)

> **Describe if you have any ideas on how we may solve this**: 

just dont send the message if the player has the staff permission and is in spectator.

**Comment by BehrRiley** [comment]
this is actually a result of having a permission node and using it when they shouldn't. I personally handled this type of thing on BehrCraft by limiting it to gamemodes and less permissions than `*`, as regular players can't switch when they feel like it and my permissions were unique to every single command.
