### ISSUE TITLE
[BORK] Bossbar doesnt update on claim until changing a setting.

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#15]
Reported by Devin in discord.
![image](https://user-images.githubusercontent.com/25861695/89705180-fec0b380-d90f-11ea-9b57-608dafcdfe7e.png)

**Comment by Ph4i1ur3** [comment]
Unable to reproduce

**Comment by Ph4i1ur3** [comment]
Closing this, as it doesn't appear to be a current bug
