### ISSUE TITLE
[BORKED]economy_withdraw error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#153]
> **Error Message**:

`Tag-base 'with' returned null.`

> **Script Information**:

Script Name:  `economy_withdraw`

Script Reference:  [`survival/./repo_link/global_systems/economy_test.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/global_systems/economy_test.dsc#L94)

Script Line: 94

> **Player Attached**:

`Eutherin` / `(47951ae6-aab4-4f72-a40f-fae9003e1785`

Not sure what the problem here is. but it occurs when you try to withdraw any funds.

`    - give "<item[economy_bank_note].with[nbt=value/<[amount]>|lore=<&a>------------------------|<&e>Value<&co> <&a><[amount]>|<&e>Right click while holding to deposit.|<&a>------------------------]>"`

**Comment by Eutherin** [comment]
it also doesnt look like it actually withdraws the money from their balance >_>

**Comment by BehrRiley** [comment]
i'm seeing three different references of how money is tracked on survival, so i'm not sure what it actually uses

**Comment by Eutherin** [comment]
Feature has been fixed
