### ISSUE TITLE
[Enhancement] (Barrel Protection)

### ISSUE THREAD

**Issue by AcoshaRed** [Adriftus-Studios/network-script-data#154]
The bug is when I open a barrel or hopper in somone else claim I can steal items.

> **How To Reproduce**:

Example:
1. Go to 'Somone claim and open a barrel'
2. Click on 'barrel'

> **Expected behavior**:
 The barrel would open.

> **Additional context**:
 I can take items

**Comment by BehrRiley** [comment]
This sounds to be a feature as nothing actually prevents this from happening - adding to enhancements for protections

**Comment by Eutherin** [comment]
Addressed in pull request here:
https://github.com/BehrRiley/network-script-data/pull/120/

Thank you for your feedback.
