### ISSUE TITLE
[BORKED]claim_system_build_chunkmap error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#156]
> **Error Message**:

`Tag-base 'read' returned null.`

> **Script Information**:

Script Name:  `claim_system_build_chunkmap`

Script Reference:  [`survival/./repo_link/global_systems/chunk_claim_protection.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/global_systems/chunk_claim_protection.dsc#L1548)

Script Line: 1548

> **Player Attached**:

`GavinPlayzMC` / `(f2d5fafe-3900-46c9-946b-81475553f6c7`

**Comment by BehrRiley** [comment]
@Ph4i1ur3 re: #127
