### ISSUE TITLE
[BORKED]hide_handler error on Behrcraft

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#159]
> **Error Message**:

`Invalid definition name 'Moderators'.`

> **Script Information**:

Script Name:  `hide_handler`

Script Reference:  [`behrcraft/./repo_link/Commands/Moderation/Moderation Hide.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/behrcraft/repo_link/Commands/Moderation/Moderation%20Hide.dsc#L61)

Script Line: 61

> **Player Attached**:

`KUwUipo101` / `(e7e0d252-5d98-453e-add5-e5a12f16c076`

**Comment by BehrRiley** [comment]
Commit [`[5e60805]`](https://github.com/Adriftus-Studios/network-script-data/commit/1a24e9b80c9e7f0f562d2844023f5c0e0c666f42) fixed this a few days ago already
