### ISSUE TITLE
[BORKED]store_hub_mysteryshop_boxes_events error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#160]
> **Error Message**:

`Tag-base 'read' returned null.`

> **Script Information**:

Script Name:  `store_hub_mysteryshop_boxes_events`

Script Reference:  [`survival/./repo_link/shops/Mystery_Shop.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/shops/Mystery_Shop.dsc#L99)

Script Line: 99

> **Player Attached**:

`smurphy1996` / `(8f06bba3-d40f-44e3-92b1-f14318ed6581`

**Comment by BehrRiley** [comment]
This may be the result of a player not having the `economy.premium.current` key within their global player data, I don't even know what this is. I'd recommend checking if the yaml contains this path, or not.

**Comment by Eutherin** [comment]
I think its for the adriftus coins
