### ISSUE TITLE
[BORKED] tutorial_events error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#164]
> **Error Message**: `Invalid context ID 'entity'!`
> **Script Name**: `tutorial_events`
> **Script Reference**:  [`survival/./repo_link/spawn_scripts/tutorial.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/spawn_scripts/tutorial.dsc#L294)
> **Script Line**: `294`
`- if <context.entity.name> == ContinueTutorial:`
> **Player Attached**: `AlexDez` / `933f17c3-d583-4090-9c5d-3f07b93f4142`

**Comment by BehrRiley** [comment]
Does this have to do with the player logging in any way? Is this easy to replicate?

**Comment by Eutherin** [comment]
Not sure tbh, we adjusted distances yesterday, hopefully that will help?
