### ISSUE TITLE
Tutorial bork

### ISSUE THREAD

**Issue by Grumblin** [Adriftus-Studios/network-script-data#165]
New players do not get put into the tutorial on first log in

players can use /tutorial from anywhere, even in combat. This is not ideal.

**Comment by Eutherin** [comment]
Is this the same player that issue#164 is from? We should utilize that in combat flag to check when teleporting(when the item exists), spawning, or homing. Shouldnt be too hard of a fix.

**Comment by Eutherin** [comment]
https://github.com/Adriftus-Studios/network-script-data/issues/164
