### ISSUE TITLE
[BORKED] command_syntax error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#168]
> **Error Message**: `Tag <queue.script.parsed_key[Usage]> is invalid!`
> **Script Name**: `command_syntax`
> **Script Reference**:  [`global/dependencies/command_dependencies.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/global/server/dependencies/command_dependencies.dsc#L11)
> **Script Line**: `11`
`entry[script].result.split[<&nl>].get[<[Script_Line]>].trim`
> **Player Attached**: `TarasTech` / `b2b9aada-f07b-4bbf-864b-672cafdb2612`

**Comment by BehrRiley** [comment]
This is the result of a command not having the usage or description key specifically, there's no changes that need to be done to the script that fired this error here. It's misuse of the dependency

**Comment by BehrRiley** [comment]
I'd recommend running through the different command script containers to verify they have both of the required keys; ` usage` and `description`
