### ISSUE TITLE
[BORKED] chat_command error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#169]
> **Error Message**: `Woah! Invalid arguments were specified!`
> **Script Name**: `chat_command`
> **Script Reference**:  [`global/chat.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/global/server/chat.dsc#L85)
> **Script Line**: `85`
`entry[script].result.split[<&nl>].get[<[Script_Line]>].trim`
> **Player Attached**: `Mutim_Endymion` / `820accf7-c943-40ff-beb2-961533406efa`

**Comment by BehrRiley** [comment]
The command line is missing the definition name `reason`

**Comment by BehrRiley** [comment]
Fixed in [`[5f1bab]`](https://github.com/Adriftus-Studios/network-script-data/compare/5f1bab5ad21a...2f26264b613c).
