### ISSUE TITLE
[BORKED] command_error error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#170]
> **Error Message**: `Invalid definition name 'Reason'.`
> **Script Name**: `command_error`
> **Script Reference**:  [`global/dependencies/command_dependencies.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/global/server/dependencies/command_dependencies.dsc#L25)
> **Script Line**: `25`
`entry[script].result.split[<&nl>].get[<[Script_Line]>].trim`
> **Player Attached**: `Mutim_Endymion` / `820accf7-c943-40ff-beb2-961533406efa`

**Comment by BehrRiley** [comment]
This is a duplicate to #169
