### ISSUE TITLE
(Feature Request) Teleport Request Command

### ISSUE THREAD

**Issue by Indestructoyed** [Adriftus-Studios/network-script-data#171]
To whom it may concern,

The server is an unofficial Factions server in where you can add people to your groups and have have friends play with you. The server itself is extroidinarilly magnificent but it makes it hard to get to your friends and play with them with out a teleport command, so here I give you a concept:

/tpr: Allows for a player to send a request to another player, to which the recipient would get an option to accept or deny the request in question and then be transported to the recipient.

/tprhere: Would do the above but instead the recipient would be transported to the player.

Thank you for taking the time to consider my request and I hope you have a most wonderful rest of your day.

Sincerely,
Indestructoyed

**Comment by Eutherin** [comment]
Teleport is currently planned to be a consumable item you can craft after defeating the end dragon.

**Comment by BehrRiley** [comment]
Duplicate to #87 #88
