### ISSUE TITLE
Pay command issues 

### ISSUE THREAD

**Issue by Grumblin** [Adriftus-Studios/network-script-data#173]
![image](https://user-images.githubusercontent.com/59983106/97501882-75d27a80-1948-11eb-8d82-b2a076d3f2c6.png)
When being paid, it says your name not the person who paid you; in this picture I was paid by drew but says i was paid by myself

Pay needs to have username auto complete

**Comment by BehrRiley** [comment]
would recommend using the dependency we have configured for the tab completion;

you may want to also verify whether the paid amount is a negative number, the player paying is not also the player receiving the payment, as well as potentially is an obnoxious decimal larger than our currency's decimal placement. (eg; `/pay _behr 0`, `/pay _behr -10000`, or `/pay _behr 0.2147483647`)
