### ISSUE TITLE
claims protections

### ISSUE THREAD

**Issue by Grumblin** [Adriftus-Studios/network-script-data#174]
Barrels can still be accessed
Bookshelves can still be accessed
You can pop items out of item frames
Minecarts of all kinds can be broken in claims not your own
Can still access hoppers and hopper minecarts
Can access minecart chests
Can place minecarts on rails that already exist in peoples claims

**Comment by BehrRiley** [comment]
barrels and bookshelves are resolved now from [`[]`]()

> `You can pop items out of item frames`
this requires the `entity breaks hanging` event be cancelled

> `Minecarts of all kinds can be broken in claims not your own`
this requires the `entity kills minecart` event, and verifying the entity is a player, or the projectile is an arrow from a player, potentially

> `Can access minecart chests` / `Can access minecart chests`
this requires the `player right clicks entity` event be cancelled

> `Can place minecarts on rails that already exist in peoples claims`
this requires the `player clicks block` event be cancelled when the `with` switch is toggled for `minecart`
