### ISSUE TITLE
Graves issue - need to look into it

### ISSUE THREAD

**Issue by Grumblin** [Adriftus-Studios/network-script-data#175]
Dying in a claim sometimes doesn't spawn a grave, not sure what brings this on

**Comment by Eutherin** [comment]
Did the player have items in their inventory?

**Comment by Eutherin** [comment]
@Grumblin is this still occuring

**Comment by Eutherin** [comment]
Could not replicate
![image](https://user-images.githubusercontent.com/25861695/102009257-0a235180-3ceb-11eb-9e17-d3375041bb50.png)
