### ISSUE TITLE
[BORK] Grappling hook 

### ISSUE THREAD

**Issue by Grumblin** [Adriftus-Studios/network-script-data#177]
> **Describe the bug**: Glitching through walls with the grappling hook

> **How To Reproduce**:

Get hook
Walk slightly away from wall
use hook
walk slightly forward then slightly backward
you will walk backwards through the wall

> **Expected behavior**:

To not walk through walls

**Comment by BehrRiley** [comment]
are you physically clipping through walls like in a `no-clip` style, as if it were actually air and the material is still present like in spectator mode?
