### ISSUE TITLE
[BORK] Adding self to claim

### ISSUE THREAD

**Issue by Grumblin** [Adriftus-Studios/network-script-data#178]
> **Describe the bug**:
You are able to add yourself to claim which prevents you from doing anything in that claim or deleting that claim

> **How To Reproduce**:

Add yourself to the claim
???
Die a lonely death with only 29 available claim spots

> **Expected behavior**:

To not be able to add yourself to your own claim

**Comment by Eutherin** [comment]
can they remove themselves from the claim?

**Comment by BehrRiley** [comment]
Commit [`[a666c98]`](https://github.com/BehrRiley/network-script-data/commit/a666c98e3c6f53c4a4607e96eb9d2d85ac3fe410) resolves this.
