### ISSUE TITLE
[BORK] Sniping animals out of peoples claims

### ISSUE THREAD

**Issue by Grumblin** [Adriftus-Studios/network-script-data#179]
> **Describe the bug**:
If you are standing in your own claim, or in the outerlands, and a claim has animals in them, you can stand outside of that claim and snipe the animals out of the claim with the grappling hook

> **How To Reproduce**:

Have hook
Stand outside of claim that you want to snipe animals from
Snipe animals
Profit on wool

> **Expected behavior**:

Hook not being able to steal peoples animals 

> **Screenshots**:

![image](https://user-images.githubusercontent.com/59983106/97522198-949b3600-1975-11eb-8819-4316b10a8bdb.png)
I've taken a sheep from this claim by not being in their claim

**Comment by Eutherin** [comment]
"snipe"

Could not replicate with a bow
