### ISSUE TITLE
[BORKED] claiming_protection_events error on Survival 1197

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#184]
> **Error Message**: `Invalid definition name 'group'.`
> **Script Name**: `claiming_protection_events`
> **Script Reference**:  [`survival/./repo_link/global_systems/chunk_claim_protection.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/global_systems/chunk_claim_protection.dsc#L1197)
> **Script Line**: `1197`
> **Player Attached**: `Dylans17` / `70381fff-3f89-446c-a4e3-30138577f7f3`

**Comment by Eutherin** [comment]
@Ph4i1ur3 the event on 1178 has a different definition from 1203. Could that be the cause here?

**Comment by BehrRiley** [comment]
No, it just doesn't have `group` defined. It was just added here: [`[98b9da7]`](<https://github.com/Adriftus-Studios/network-script-data/commit/b2b8ba897f50bad19c8e626a64a2c6f588049bd1>)

I believe it needs this context:
```yml
    - define location <context.location||<player.location>>
    - define group <yaml[claims].read[<[location].chunk.world>.<[location].chunk.x>.<[location].chunk.z>]||null>```

**Comment by Eutherin** [comment]
Thats what I was thinking. Theres a _lot_ of events missing that definition, that may be the root cause.
