### ISSUE TITLE
[BORK] (Free Bowtrails)

### ISSUE THREAD

**Issue by Cryotea** [Adriftus-Studios/network-script-data#185]
> **You can Buy Bowtrails without having Adriftus Coins**:

> **How To Reproduce**:

1. Go to The Cosmetic Shop
2. Click on BowTrails
3. Click on Any BowTrail

> **Expected behavior**:
You Shoudnt get the Bow trail without Coins

**Comment by BehrRiley** [comment]
I don't believe they have a set cost coming out from beta.

**Comment by Eutherin** [comment]
They are in fact supposed to carry a cost:
![image](https://user-images.githubusercontent.com/25861695/97677693-e617f380-1a4f-11eb-8f94-83a942371f97.png)

**Comment by Eutherin** [comment]
@Ph4i1ur3 I cant find where `price` is defined.

**Comment by BehrRiley** [comment]
> `I cant find where price is defined.`

the script does not define it - it's not coded in and was intended to be free during beta, is what i meant

**Comment by Eutherin** [comment]
So we need to add it to an nbt on the bowtrials data storage?

**Comment by ChrispyMC** [comment]
Should they all have the same price?
