### ISSUE TITLE
[BORKED] RTP death

### ISSUE THREAD

**Issue by Dylans17** [Adriftus-Studios/network-script-data#186]
An intended feature of RTP is a cooldown after repeated use. However, the way this is handled is by sending the player to their home without fall damage protection. A natural consequence of this is death.

How to reproduce:
1) Be sure to have your home set using /sethome. It may or may not be necessary to have your home in a 1 or 2 high gap.
2) Go to /spawn. Jump off the edge.
3) Repeat step 2 until you get sent home. Make sure to know how many times you jumped.
4) Go to /spawn
5) Wait for the last cooldown for no fall damage. (You should have the same number of fall damage messages as the number of jumps/RTP's)
6) Jump and attempt RTP, you should then be returned to your home dead.

Potential Solutions:
1) Offer no fall damage in all cases and not just when RTP is successful,
2) Return to somewhere where you do not take fall damage (such as spawn).

**Comment by Eutherin** [comment]
Why does it matter how many times you've jumped?

We will have to investigate this as its supposed to send you home instead of giving you the opportunity to fall. 

We intentionally made it send the player home instead of back to spawn.

**Comment by Eutherin** [comment]
Also, did the template not apply [BORK] correctly, or was a template not used?

**Comment by BehrRiley** [comment]
I think the recommendation here is that they would like to be safely sent to their home in the case they are experiencing a cool-down; it sounds as if they killed themselves with the velocity gained from jumping in hopes to RTP but were instead teleported to their home, dying from the impact of the fall

**Comment by Eutherin** [comment]
Does teleport not clear your velocity? Maybe we should set velocity to 0, or just give like 3s of protection.

**Comment by BehrRiley** [comment]
we can also determine the fall damage cancelled as we do for RTP, few different options, open to all of them

**Comment by Eutherin** [comment]
Let's pop in to dev chat.
