### ISSUE TITLE
[BORKED] silk_spawners error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#188]
> **Error Message**: `Tag <context.material.item.with[display_name=<[Type]><&sp>Spawner;nbt=key/<[Type]>]> is invalid!`
> **Script Name**: `silk_spawners`
> **Script Reference**:  [`survival/./repo_link/systems/SilkSpawner.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/systems/SilkSpawner.dsc#L9)
> **Script Line**: `9`
> **Player Attached**: `Eutherin` / `47951ae6-aab4-4f72-a40f-fae9003e1785`

**Comment by Eutherin** [comment]
https://github.com/BehrRiley/network-script-data/pull/131

**Comment by pjochillin** [comment]
In this script, they use the mechanism `ItemTag.display_name,` which should be `ItemTag.display.` I will PR the fix soon.

**Comment by Eutherin** [comment]
Script removed
