### ISSUE TITLE
[BORK] backpacks should not be renamed

### ISSUE THREAD

**Issue by TarasTech** [Adriftus-Studios/network-script-data#190]
> **Describe the bug**:
You can rename a backpack in an anvil

> **How To Reproduce**:

Example:
1. Goto an anvil
2. Place backpack in anvil
3. Change name of backpack in anvil
4. Take backpack out of anvil

> **Expected behavior**:

Renaming backpack event should be cancelled

> **Screenshots**:

> **Additional context**:

**Comment by Eutherin** [comment]
Cannot cancel, determining insanely high xp cost.
