### ISSUE TITLE
(Feature Request) Number of claims available should be shown somewhere in the /claims gui

### ISSUE THREAD

**Issue by TarasTech** [Adriftus-Studios/network-script-data#191]
> **The Type of request**:

This is a simple informational addon to one of the guis

> **Who is requesting this**:

TarasTech - Member of Junk

> **Describe the feature**:

There is no way to tell how many claim chunks i have available unless I'm actually claiming chunks.
The claims menu should have some sort of info about that

> **Describe the impact**: 

It will make it easier to know how many claim chunks you have avialable

> **Describe the reach of this feature**:

Everyone playing survival

> **Describe the cost of not doing this request**: 

Fidning how many chunks you have available will be annoying

> **Describe which goals this helps**: 

The goal of knowing who has more claim chunks

> **Describe the evidence that you have on the need for this request**: 

I needed to know which member has the most chunks in our faction, and there's no way to actually tell unless you try claiming

> **Describe if you have any ideas on how we may solve this**: 

ADD INFORMATION TO GUI

> **Describe how urgent this is and why**: 

I mean its not too urgent, but would be nice to have

**Comment by Eutherin** [comment]
![image](https://user-images.githubusercontent.com/25861695/97866407-b6bbed80-1cc0-11eb-9b2f-df34b4f0bbaf.png)
Please clarify.
