### ISSUE TITLE
[BORK] Autoplant does not replant netherwart

### ISSUE THREAD

**Issue by TarasTech** [Adriftus-Studios/network-script-data#192]
> **Describe the bug**:

When a claim owns the autoplant upgrade, it does not autoplant netherwart

> **How To Reproduce**:

Example:
1. Buy autoplant
2. plant netherwart
3. wait for it to grow
4. break
5. it does not replant

> **Expected behavior**:

It should replant

> **Screenshots**:

![image](https://user-images.githubusercontent.com/26036013/97823773-c874a500-1c6e-11eb-9167-61fff1efdec7.png)

> **Additional context**:

Idk

**Comment by Eutherin** [comment]
https://github.com/BehrRiley/network-script-data/pull/133

**Comment by Eutherin** [comment]
man i always do that backwards lol

**Comment by BehrRiley** [comment]
Commit [`[a2bc4f9d]`](https://github.com/BehrRiley/network-script-data/pull/133/commits/a2bc4f9dacf1a5e250d1964a808b1358a43af9f2) resolves this request.
