### ISSUE TITLE
[BORKED] survivalistinventoryinject error on Survival

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#196]
> **Error Message**: `Tag-base 'item' returned null.`
> **Script Name**: `survivalistinventoryinject`
> **Script Reference**:  [`survival/./repo_link/shops/survivalist_shop.dsc`](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/shops/survivalist_shop.dsc#L34)
> **Script Line**: `34`
> **Player Attached**: `Jsspedersen` / `18c340f1-da48-4ce4-8962-429cb4776c77`

**Comment by Ph4i1ur3** [comment]
Result of #199, will be fixed by fixing that issue
