### ISSUE TITLE
[BORK] players able to place grappling hooks

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#199]
> **Describe the bug**:

Dylans17 reported he is able to place his grappling hook and lose the iten.

> **How To Reproduce**:

Place the itme

> **Expected behavior**:

Should be cancelled

> **Screenshots**:

> **Additional context**:

 Reported by Dylans17

**Comment by Grumblin** [comment]
To add to this, grappling hooks don't currently operate at all, and are not in the survivalist shop for purchase

**Comment by Ph4i1ur3** [comment]
Graplling hook script was broken by a PR, will be fixed tonight.
