### ISSUE TITLE
(Feature Request) warps

### ISSUE THREAD

**Issue by jsspedersen** [Adriftus-Studios/network-script-data#200]
I've been wondering if there's been any talk about making warps in the nether as well as a claim system if not that's what I'm suggesting. would pretty much work just like the claim and warp system as in the over world. the only thing i would suggest to make different is a separate GUI menu for overworld and nether.

discord:jsspedersen#0450

**Comment by Eutherin** [comment]
@Ph4i1ur3

**Comment by Eutherin** [comment]
See the above pull request, nether claims will be in that patch.
