### ISSUE TITLE
[BORK] Adriftus butler announcer messed up.

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#22]
> **Describe the bug**:

![image](https://user-images.githubusercontent.com/25861695/89705850-79400200-d915-11ea-80d5-037bda98de53.png)

> **How To Reproduce**:
Right click on the butler.

**Comment by pjochillin** [comment]
I'm right-clicking on the NPC specified above, and I am not receiving the default NPC text message. It could've been fixed without recognition or because of permissions maybe?

**Comment by BehrRiley** [comment]
This is due to you having permissions that players do not.
While it's not exactly a breaking bug that players will be able to see, we need to disable the NPC chat that someone must've turned on.

**Comment by BehrRiley** [comment]
Removed the trait from the NPC.
