### ISSUE TITLE
[BORK] (Can steal people stuff in item frames)

### ISSUE THREAD

**Issue by AcoshaRed** [Adriftus-Studios/network-script-data#222]
> **My friend clicked on 1 of our item frames and it took the item**:

> **How To Reproduce**:

Example:
1. Go to somone item frame'
2. Click on 'it'
3. Scroll down to then you have the item'

> **Expected behavior**:

> **Screenshots**:

> **Additional context**:

**Comment by Eutherin** [comment]
I believe this has been resolved. Can you nondestructive test it? Or provide an item frame location on discord for me to test with?

**Comment by Eutherin** [comment]
Seems to have been resolved.
