### ISSUE TITLE
[BORK] Marketplace warp name coloring messed up

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#27]
![image](https://user-images.githubusercontent.com/25861695/89718745-4aa64380-d976-11ea-92fb-5165215d5670.png)
If we're sticking with the coloring scheme this is inconsistent.

**Comment by ChrispyMC** [comment]
This issue should be closed as it is [already fixed](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo-link/global_systems/warps.dsc#L17).

**Comment by BehrRiley** [comment]
Fixed per: https://github.com/Adriftus-Studios/network-script-data/commit/1cf698c82164ca230fba9c0d3b744d1150b7dc18
