### ISSUE TITLE
Particle animation for tutorial popups

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#28]
![9bcfa449aa61f27a1a54bf5d37e98e31](https://user-images.githubusercontent.com/46008563/89721167-3a0ec100-d9a8-11ea-8395-73cc96767cdc.gif)

behr has done this already. 
~~https://discordapp.com/channels/626078288556851230/626080540638052382/739870532794581023~~
edit: replacing discord link with a gif:
https://i.gyazo.com/9bcfa449aa61f27a1a54bf5d37e98e31.gif

**Comment by ChrispyMC** [comment]
[Line 252 of tutorial.dsc](https://github.com/Adriftus-Studios/network-script-data/blob/master/denizen_scripts/survival/repo_link/spawn_scripts/tutorial.dsc#L252) is where the playeffect command would be under. PlayEffect's `location` can take a list of location tags. This means the particles can be made to span the length of the hologram text.
