### ISSUE TITLE
Global Script | Network Teleport Command

### ISSUE THREAD

**Issue by BehrRiley** [Adriftus-Studios/network-script-data#3]
Command that allows a player to directly teleport to another player across servers within the network, as well as a command that teleports another player to you.

 ### Resources Needed:
- [ ] Script or system that can return the network's players with their current server, optimally a map with the player, their current server and their location.
- [ ] Optimally, a settings command with a setting feature to allow/disallow instant friend teleports.
- [ ] A system that determines permissions across the network that would validate sections of this command
- Implementing and determining a Network Event Manager to add value to a `teleport everyone` type command

### Command Syntax:
Teleport Command:
- [ ] `/tp (<Player> (<Player>)/(everyone/all) <Player>) (-r/-request/request)`
aliases: `/ntp` | `/networktp` | `/servertp`

TeleportHere Command:
- [ ] `/tp (<Player>(,...)/(everyone/all)) (-r/-request/request) (-s/-server/-l/-local/-locally)`
aliases: `/ntph` | `/networktphere` | `/servertphere`

### Command Argument Usage:
**Direct Teleport**:
- [ ] `/tp Player` | Teleports, or requests to teleport you to `Player`.

- [ ] `/tp Player1 Player2` | Teleports `Player1` to `Player2`, requires `.teleport.others` permission.
- [ ] `/tp Player1 -r` | Overrides Instant permissions to request to teleport to `Player1`.
- Request Alias:
  - [ ] `/tpa Player1` | Alias `/tp Player1 -r` - for Overrides Instant permissions to request to teleport to `Player1`.

- [ ] `/tp everyone Player` | Teleport, or requests to teleport everyone on the network to `Player`.
- [ ] `/tp everyone -r` | Overrides instant permissions to request all players on the network to teleport to you.
- [ ] `/tpa everyone` | Alias for `/tp everyone -r` - Overrides instant permissions to request all players on the network to teleport to you.

- [ ] `/tp everyone Player -s` | Teleport, or requests to teleport everyone on the current server to `Player`.
- [ ] `/tp everyone -r -s` | Overrides instant permissions to request all players on the current server to teleport to you.
- [ ] `/tpa everyone -s` | Alias for `/tpa everyone -r -s` - Overrides instant permissions to request all players on the current server to teleport to you.

**Teleport Here**:
- [ ] `/tphere Player` | Teleports, or requests to teleport `Player` to you.
- [ ] `/tphere Player1,Player2` | Teleports, or requests to teleport `Player1` and `Player2` to you.

- [ ] `/tphere Player1 -r` | Overrides instant teleport permissions and requests to teleport `Player1` to you.
- [ ] `/tphere Player1,Player2 -r` | Overrides instant teleport permissions and requests to teleport `Player1` to you.
- Request Aliases:
  - [ ] `/tpahere Player1` | Alias to `/tphere Player1 -r` - Overrides instant teleport permissions and requests to teleport `Player1` to you.
  - [ ] `/tpahere Player1,Player2` | Alias to `/tphere Player1,Player2 -r` - Overrides instant teleport permissions and requests to teleport `Player1` to you.

- [ ] `/tphere Everyone` | Teleports, or requests to teleport everyone on the network  to you.
- [ ] `/tphere Everyone -r` | Overrides instant teleport permissions and requests everyone on the network to teleport everyone to you.
- Request Aliases:
  - [ ] `/tpahere Everyone` | Alias to `/tphere Everyone -r` - Overrides instant teleport permissions and requests everyone on the network to teleport everyone to you.

- [ ] `/tphere Everyone -s` | Teleports, or requests to teleport everyone on the current server to to you.
- [ ] `/tphere Everyone -r -s` | Overrides instant teleport permissions and requests everyone on the current server to teleport everyone to you.
- Request Aliases:
  - [ ] `/tpahere Everyone -s` | Alias to `/tphere Everyone -r -s` - Overrides instant teleport permissions and requests everyone on the current server to teleport everyone to you.

### Command Checks:
- [ ] Verify if a player has permission on the server they're on to use the teleport command.
- [ ] Verify if the target player's server if it allows the teleport to income.
- [ ] Verify if the player is a moderator+ to determine if this is will be a request or an instant teleport.
  - [ ] If Request: Verify if the player is a friend, and if they have `instant teleport request`s enabled.
- [ ] Check if the location is safe (eg, the location is on `air`, the first block between the location and the next non-air block below is lava, the teleport is not safe).
- [ ] Check if the target player is already receiving a teleport request from the player.
- [ ] Check if the player is already requesting to teleport to a different target player within a time period.
  - [ ] Prompt to cancel last teleport request if so.
- [ ] `Everyone` would be strictly Network Event managers and Administration

**Comment by Ph4i1ur3** [comment]
I think this would be a bad idea, given the different nature of each server being wildly different.
