### ISSUE TITLE
[BORK] parkour script does nothing when completed.

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#30]
Can it at least unlock the parkour title?

**Comment by pjochillin** [comment]
Added this feature to my pull request; #14 on Behr's fork (not this one)

**Comment by pjochillin** [comment]
This should be fixed with [https://github.com/BehrRiley/network-script-data/pull/33](url), rewarding the `Flashyjumper` title on parkour completion.

**Comment by ChrispyMC** [comment]
This issue should be closed as pjo's above pull request has already been merged. https://github.com/BehrRiley/network-script-data/pull/33.
