### ISSUE TITLE
[BORK] (Can not break sponge)

### ISSUE THREAD

**Issue by Dylans17** [Adriftus-Studios/network-script-data#336]
> **Describe the bug**:

You cannot break wet or dry sponge once placed.

> **How To Reproduce**:

1. Place sponge
2. Try to break the sponge
3. Breaking action is denied server-side

> **Expected behavior**:

The sponge breaks and the item drops.

**Comment by Dylans17** [comment]
Fixed somehow

**Comment by Eutherin** [comment]
had an errant script requesting something that didn't exist, script was yeeted
