### ISSUE TITLE
Mail system for messaging offline players

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#37]
Pretty much the same as the title, its a pretty standard feature in most server management plugins.

**Comment by BehrRiley** [comment]
<img width="250" alt="mailheads" src="https://user-images.githubusercontent.com/46008563/89741044-f1b0db00-da5b-11ea-9f8e-5e1ce64e1c0d.PNG">
found a variety of heads that would give a good look for packages, mail and mailboxes
