### ISSUE TITLE
/Food - Discord Command...

### ISSUE THREAD

**Issue by BehrRiley** [Adriftus-Studios/network-script-data#39]
...Literally just a command that randomly returns a list of places to eat ... I guess.

Optimal features that would make this more valuable:
- [x] Random Food Return (The primary request)
- [x] Add extra foods to a list to randomize between with an `Add` argument
- [ ] Specifying a number to receive a list of places to eat as opposed to just one thing
- [ ] Specifying either a restaurant or a whonky combination of food/beverage/concoction of consume-able substance
- [ ] Shot Quantity Randomizer - return a random integer for shots to take.

**Comment by sibraxlis** [comment]
Why did you close, its not done.

Also, /food list please to see all entries

**Comment by sibraxlis** [comment]
Also /food hell

**Comment by pjochillin** [comment]
Added /food help, /food list, /food shots (to generate shot numbers), /food remove, and /food (<#>) to receive a list of foods (rather than one).
Refer to [https://github.com/BehrRiley/network-script-data/pull/32](url) for more information.
