### ISSUE TITLE
Mob scaling script.

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#41]
Need the script to scale the mob levels, or do you want me to take care of it in ~~MM~~ Mythic Mobs.

**Comment by sibraxlis** [comment]
20k blocks, 10 levels, should put us at 1 level every 2k blocks, with mobs in the dead center maze being set to 10.

**Comment by BehrRiley** [comment]
@Ph4i1ur3 mentioned that we should handle spawning with Denizen, and using Mythic Mobs for the mob AIs.

**Comment by Ph4i1ur3** [comment]
MM should handle the mobs themselves, A denizen script should be used to handle the actual spawning, flowing the logic above. Mobs outside the 20k should be left Vanilla

**Comment by Ph4i1ur3** [comment]
As further annotation, the mobs inside the dungeon should be different (harder) than the mobs in the overworld.

**Comment by Eutherin** [comment]
Already have plans for mobs inside the dungeon (Faster, knockback immune)

**Comment by Ph4i1ur3** [comment]
Implemented in #74
