### ISSUE TITLE
[Survival+] Creating Issues for Alpha/Release

### ISSUE THREAD

**Issue by Mutim** [Adriftus-Studios/network-script-data#44]
Things that we need to get done before release. This shouldn't even take us Two Weeks™

This is a quick and dirty outline of what's needed for release. I'll try to grab everything and keep it all simplified to the most important issues that need to be tackled. 

NOTE: These things can be handled by different people, so don't think of this as a linear checklist or in any order.

- ~~Fill the middle maze~~

- [x] Add mobs to scale starting at 25k (I think 25k) **Edit**: See #41 

- ~~Add the 4 guardians in front of the tower~~
  - ~~Waiting on Xeane's response as to what these are~~ Xeane has no idea what this is. Ignoring

- ~~General testing of systems, doing a quick bug check ( ie. the dragon doesn't spawn on the tutorial)~~

- [x] Code the end dragon fight **Edit**: See #47 

- ~~Code the puzzles (Think of the puzzles)~~
     - ~~talked about in #Design-Chat~~
     - ~~Some ideas are in the pins :read_the_pins: . This is dynamic, as we don't have anything set in stone yet.~~
     - [ ] One puzzle room:
       - room has a giant hole in the middle (Filled with sand), you have to cross it
       - switch them to adventure mode (They'll be in adventure when they drop into the maze)
       - the path is showfaked barrier (Showfaked real path)
       - one potion on a table onfront of the chasm (yep)
       - the drinker can see the barriers as a non-solid block

- [ ] Hub completed. 
     - ~~This is builds, code, shops, integration. Making it look good on first join. ~~ 
      - Waiting for more info regarding shops and other integration or whatever else needs to be here

**Comment by BehrRiley** [comment]
Created the issue #41 for better organizing this issue

**Comment by BehrRiley** [comment]
@Grumblin created the issue #47 for the end dragon fight.
