### ISSUE TITLE
[Survival+](Feature Request) Scroll of Travel & Teleport Crystals

### ISSUE THREAD

**Issue by BehrRiley** [Adriftus-Studios/network-script-data#46]
Items to implement:
- [ ] Scroll of Travel
- [ ] Teleport Crystals
Item would be a drop from killing the ender dragon; a 5% drop-rate chance which unlocks the ability to buy teleport crystals in the consumables shop

Would also be added as a rare drop rate for mobs

Item would be a consumable based item

Teleport Crystals would be essentially `/tpahere` / `/tpa` for players to create teleport requests between players.

Would propose the following sets of code where `Other_Player` is the name of the player that a player enters for teleport requests
Using the `Player_Verification` dependency:
```yml
- define User <[Other_Player]>
- inject Player_Verification
```
as well as the two sets of maps in flags:
```yml
# Request to teleport a player to you
- define Teleport_Map <map.with[<player>].as[<map.with[Request_Type].as[Teleport_Here].with[Location].as[<player.location>]>]>
- flag <[Other_Player]> Flag_Name:->:<[Teleport_Map]> duration:3m
- flag <player> Flag_Name:->:<map.with[<[Other_Player]>].as[<[Teleport_Map].with[Request_Type].as[Teleport_To]>]> duration:3m
```
```yml
# Request to teleport to another player
- define Teleport_Map <map.with[<player>].as[<map.with[Request_Type].as[Teleport_To].with[Location].as[<player.location>]>]>
- flag <[Other_Player]> FlagName:->:<[Teleport_Map]> duration:3m
- flag <player> FlagName:->:<map.with[<[Other_Player]>].as[<[Teleport_Map].with[Request_Type].as[Teleport_Here]>]> duration:3m
```
Essentially defining request types as `Teleport_To` and `Teleport_Here` for requests
The reason for flagging both players is for if PlayerB requests to teleport the same type of teleport to PlayerA, then instead of a request we can initiate the teleport instead of having two of the same teleport request

**Comment by ChrispyMC** [comment]
`Scroll of Travel` -> `Recipe: Teleportation Crystal`
[Message Link](https://discord.com/channels/626078288556851230/669922990435336216/745688583179862026).

**Comment by ChrispyMC** [comment]
`A 5% drop-rate chance which unlocks the ability to buy teleport crystals in the consumables shop` -> `Unlocks ability to craft teleport crystals using items that players have to buy in a shop.`

**Comment by ChrispyMC** [comment]
If PlayerA requests that PlayerB teleports to PlayerA's location, and PlayerB requests to teleport to PlayerA's location, then a teleport should occur.
