### ISSUE TITLE
Dragon Fight

### ISSUE THREAD

**Issue by Grumblin** [Adriftus-Studios/network-script-data#47]
Let me paint you a picture, a wonderful picture, the most wonderful picture that you have ever seen, the greatest picture, some would say, because I know pictures and I can say that this is the greatest picture because this is the greatest picture if I do say so myself, I know the most about pictures in the world, no one knows more about this picture than I do.

stage 1:
- [ ] **Dragon intro**
  - [ ] Dragon curled up in the middle, sleeping
  - [ ] Dragon doesn't wake up until an item (dropped by a miniboss) is used on him
  - [x] The dragon will start awakening by summoning loads of mobs
    - [x] Players must kill 50 of them to continue the fight
    - [x] Mobs will drop the following items with custom NBT so they are removed at the end of the fight
      - [x] Arrow of Harming
      - [x] Spectral arrow
      - [x] Stackable splash potions of instant harming (these cannot deal damage to the dragon)

Stage 2:
- [ ] **Crystals + basketball + raining fire**
  - [ ] Dragon flies into the sky and is immune to damage, he is raining the fire types down based on the active crystals
  - [ ] The crystals spawn in in a random order each time you fight the dragon
  - [ ] **4 crystals**
    - [ ] While these are up, mobs will be spawning that drop the required items to deal damage to them
    - [ ] Every 3 minutes, one of the crystals awakens or immediately after the last one has died.
      - [ ] on awaken, it will spawn a floating entity above it and change the light grey glass to it's relevant colour 
    - [x] **Purple crystal (north)**
      - [x] While active, elite endermen will spawn occasionally (time undetermined) - when killed they will drop an AoE pool around their death point that, when a player stands in it, will allow the player to deal damage to the crystal
      - [x] The crystal is only damageable by arrows of harming 
    - [ ] **Green crystal (east)**
      - [x] While active, this crystal has a gas cloud around it
        - [x] stepping into this will cause an action bar counter to start going to 100%. stepping out of the fog starts decreasing that %
        - [ ] players with the "Temptations Defeat" buff do not take damage from the fog no matter what
      - [x] Crystal can only be damaged by melee damage
    - [ ] **Yellow Crystal (south)**
      - [ ] The crystal has a rotating shield around it, players must time their shots to get it in when the shield is open
      - [x] Crystal can only be damaged by spectral arrows
    - [x] **Red Crystal (west)**
      - [x] Crystal can only be damaged by splash potions of instant harming
  - [ ] **Dragon's fire**
    - [ ] **Purple fire**
      - [ ] When this happens, anyone who is hit by the attack will immediately be dealt damage equal to 75% of their current health
      - [ ] Anyone hit will be marked with the "Stare into the Void" debuff 
        - [ ] This will gradually black out the players screen
        - [ ] This debuff can be passed between players by bumping into them. When passed, the effect resets itself. The buff cannot be passed back to the person who just gave it to you. 
        - [ ] When Purple (north) crystal dies, it will have an AoE pool around it for 45 seconds where anyone who has the buff can go to to clear the effect. Players must stand in the pool for 5 seconds to clear it. 
    - [ ] **Green fire**
      - [ ] If anyone is hit by this fire, they will gain the 'temptations benefit' debuff, which will randomly teleport them closer towards the edge of the map, eventually leading them to suicide
      - [ ] Another player is randomly marked with the 'temptations defeat' buff, if the two players get near each other then both of the effects will be cleared and the buff will randomly go to another player
      - [ ] only 1 player can have the 'temptations defeat' debuff at one time
    - [x] **Golden fire**
      - [x] If a player is hit by this fire, they will be sent to the spectral plane where they must kill 10 mobs to be brought back
    - [ ] **Red fire**
      - [ ] Players hit by this will perpetually burn, this can be passed between players by bumping into each other but does not go out until the crystal dies
  - [ ] once all of the crystals die, there will be AoE pools around them that spawn (used in the next phase)

  - [ ] **Basketball**
    - [ ] The dragon is now hovering in place in the middle of the arena
    - [ ] This happens 3 times during the fight, once when 2 crystals have died, once when all 4 have died, and once when the dragon hits half health
    - [ ] If, by the time that you have killed 2 crystals, there are more up, those will go dormant again and any debuffs gained from them will be cleared
    - [ ] **the spectral player**
      - [ ] One player will randomly be torn into the spectral realm that exists on the island (they will not be teleported to the spectral realm, like what happens with the gold fire)
        - [ ] The player will have his inventory replaced and will be holding a single item, which causes them to also go into 3rd person from behind
        - [ ] This player is able to jump higher and hold spacebar to levitate in place
      - [ ] The spectral player will required to do platforming (not parkour) to get up to the dragon's back and slam the item into him
    - [ ] **the rest of the party**
      - [ ] There are 4 plates that appear in each of the cardinal directions
      - [ ] Players must jump onto these plates in the order that the crystals spawned, if they do it wrong the platforms for the spectral player will spawn in in the wrong order and will not be able to make it up to the drago
      - [ ] If a party member gets off a plate while the runner is on it, the runner will fall off the plate and take fall damage and the party must redo the plates from the start
      - [ ] after 5 seconds of being on the plate, a sniper will spawn in to attack the person on the plate
      - [ ] a random amount of mobs will spawn in based on how many players are in the instance at this time

Stage 3:
- [ ] Dragon fucking hates you
  - [ ] The dragon falls to the ground
  - [ ] The dragon will use melee attacks, if you are hit by these you take serious damage and your armour takes heavy durability damage
  - [ ] Every 5 hits, the dragon will launch a fireball at you that is the colour of one of the crystals
    - [ ] If you get hit by this, you need to go to that colour crystal and stand in the pool around the crystal
  - [ ] At half health, the dragon launches himself into the air again 
    - [ ] commence dunkathon v3 (this is the last time)
  - [ ] After the final dunk, the dragon drops to the ground, loses a wing, it's model changes, he takes massive damage from the fall, and starts moving towards the middle of the arena. 
    - [ ] Once the dragon gets to the middle, one player is selected to become spectral and gets moved into the spectral realm, which is exactly the same as the end island but has a crystal in the middle where the dragon is for the rest of the players
    - [ ] The non spectral players will have to deal with waves of mobs, killing a mob will drop spectral arrows in the spectral realm for the spectral player to attack the crystal with
      - [ ] The arrows do large amounts of damage to the crystal
    - [ ] Once the crystal dies, the dragon dies

Loot:
- [ ] Dragon egg
  - [ ] Once dead, a dragon egg will spawn a few blocks away from the dragon
  - [ ] The egg will display the following stats over it
    - [ ] Fight duration 
    - [ ] Player with the most damage
    - [ ] Your damage
    - [ ] Total minion kills
    - [ ] Personal minion kills
  - [ ] When right clicked, the egg will roll your loot, always giving 1 dragon soul
    - [ ] see loot table on the google doc
  - [ ] Once looted, a portal will open back to the overworld
  - [ ] Remove all of the custom NBT items

**Comment by pjochillin** [comment]
We need to figure out what is being scripted in Denizen versus what is being used in MM. We also need to find out the mechanics that will be used for the fires and if/how it can be tracked with Denizen (for effects/buffs/debuffs on damage).
