### ISSUE TITLE
/Restart - Discord Command

### ISSUE THREAD

**Issue by BehrRiley** [Adriftus-Studios/network-script-data#49]
Would be for quickly restarting servers and providing startup information.

> **Command Syntax**
- [x] `/restart` | Restarts the relay server.
- [x] `/restart <Server>` | Restarts a specified server. Would require explicit permissions to do so.

> **Command Flags**
- [x] `(-l/-log)` | Returns a log of the startup.
- [x] `(-c/-conf/-confirmation)` | Returns confirmation of when the server restart is complete.
- [x] `(-w/-d/-wait/-delay)` | Makes the command wait before issuing the server restart.
- [ ] `(-v/-version/-versions)` | Returns with confirmation when server restart is complete the version comparisons.
- [ ] `(-p/-plugin/-plugins)` | Returns with confirmation when server restart is complete the plugin comparisons. En-lists `-v` flag

> **Resources Needed**
- [x]  Some fancy webizen magic to host a direct link to the log

**Comment by Eutherin** [comment]
@BehrRiley i believe you implemented this?

**Comment by BehrRiley** [comment]
The `version` and `plugin` pieces have not been completed yet
