### ISSUE TITLE
Discord oAuth Landing Page Update

### ISSUE THREAD

**Issue by BehrRiley** [Adriftus-Studios/network-script-data#58]
After establishing the Discord URL redirect, I'd like to implement something similar to this mock-up i've created for demonstration:
![WebpageMockup](https://cdn.discordapp.com/attachments/626080540638052382/744984864306102422/unknown.png)
The left side being Adriftus could have the player's head using the Minotar API: 
![PlayerHead](https://minotar.net/cube/Behr_Riley/100.png)
essentially just: `https://minotar.net/cube/<[Player_Name]>/<[Size]>.png`

Presently, we store our tablist usernames in a format that uses hex; 
`<yaml[global.player.<server.match_player[behr].uuid>].read[Tab_Display_Name]>` returns:
`#00ff00B#4bff00e#a5ff00h#ffff00r`

Discord usernames are stored in the api that we can retrieve from oAuth or from just querying `https://discordapp.com/api/users/<[User_ID]>`. The response we recieve is:
```json
{
  "id": "194619362223718400",
  "username": "Behr",
  "avatar": "dee7262dd67443aec6bb90920625b2ba",
  "discriminator": "5305",
  "public_flags": 0
}
```
`discriminator` is fed into `<util.parse_yaml[<entry[Response].result>].get[discriminator]>` to concatenate their username (fed into `<util.parse_yaml[<entry[Response].result>].get[username]>`) to create the case-sensitive user ID: `username`#`discriminator`
`avatar` is fed into `<util.parse_yaml[<entry[Response].result>].get[avatar]>` to generate this link:
`https://cdn.discordapp.com/avatars/<[UserID]>/<[Avatar]>`
ie:
![DiscordAvatar](https://cdn.discordapp.com/avatars/194619362223718400/dee7262dd67443aec6bb90920625b2ba)

**Comment by ChrispyMC** [comment]
I'm thinking we could also retrieve a Minecraft font and apply it to the nickname text using CSS Styles.
