### ISSUE TITLE
Server Status Discord Command

### ISSUE THREAD

**Issue by BehrRiley** [Adriftus-Studios/network-script-data#6]
Command that returns various status statistics on the specified server(s) on the Network.

**Command Syntax**:
- [x] `/status (server)` | Returns whether the specified server is online, or not. Default is `Relay`.
- [x] `/status <server> (flags)` | Returns various statistics pulled directly from the specified server. Default flag is `-online`
  - [ ] Invalidates flags excluding `Online` if server returns an `Offline` status.

**Command Aliases**:
- `(status/check/onlinestatus/online)`

**Miscellaneous Args**
- [x] `/status help` | Returns a command usage display for this command.
- [x] `/status (all/servers/network)` | Returns an online status of all servers on the network against all proxied.
  - [x] Default flag is `-online`
  - [ ] `/status <all/servers/network> (flags)` | Returns the specified flags for all servers on the network currently online.
- [ ] `/status (<server>|...) (flags)` | Returns statistics for each server specified with the flags specified.

**Server Flags**:
- [x] `-o/-online` | Returns true/false whether the server is online, or not.
- [x] `-p/-players` | Returns the number of players online, and a list of each player.
  - [ ] `-disc/-discord` | Optionally include a map of each user's linked Discord?
- [x] `-w/-worlds` | Returns a list of the current world names.
- [x] `-pl/-plugins` | Returns a list of the current plugins and their versions.
- [x] `-v/-version` | Returns the server's platform version.
- [x] `-ch/-chunks` | Returns a map of world chunks and total chunks.
- [x] `-tps` | Returns the three most recent ticks per second measurements.
- [x] `-s/-scripts` | Returns a map of the server's script data.
- [x] `-a/-all` | Overrides flags input and inputs all flags.
  - [ ] This needs excessive organization, or just removed.

- [ ] Add a `Bad` flag return value, which is used against the results ran from flags. Would colorize the embed a more alarming color and emphasize warning of an alarming value.

**Comment by Ph4i1ur3** [comment]
@BehrRiley can this be closed?

**Comment by BehrRiley** [comment]
The additional flags for the command would be optimal to have, it's a big code-shift but it's a fairly easy add
