### ISSUE TITLE
/Repository - Discord command

### ISSUE THREAD

**Issue by BehrRiley** [Adriftus-Studios/network-script-data#60]
Would bring up helpful links to our repository, as well as other relevant information.

> **Command Syntax**:
`/repo` | Generates the main links we use:
- [AuroraInteractive/network-script-data](https://github.com/AuroraInteractive/network-script-data)
- [BehrRiley/network-script-data](https://github.com/BehrRiley/network-script-data)
- [Create Pull Request](https://github.com/BehrRiley/network-script-data/compare/master)
- [Adriftus Issues Page](https://github.com/AuroraInteractive/network-script-data/issues)
- [Feature Request Write-up](https://github.com/AuroraInteractive/network-script-data/blob/master/docs/contribution_docs/feature_requests.md)
- [Contribution Guide - Getting Started](https://github.com/AuroraInteractive/network-script-data/blob/master/docs/guides/1.getting-started.md)

**Comment by pjochillin** [comment]
This command was added with [https://github.com/BehrRiley/network-script-data/pull/35](url). Includes updated links with the change from Aurora-Interactive to Adriftus-Studios.
