### ISSUE TITLE
[BORKED] drop_table error on survival

### ISSUE THREAD

**Issue by Ph4i1ur3** [Adriftus-Studios/network-script-data#61]
> **Error Message**:
`Tag <script[drop_table_data].list_keys[mob_level.].numerical> is invalid!`

> **Script Information**:
Script Name:  `drop_table`
Script Reference:  [`survival/./repo-link/global_systems/drop_tables.dsc`](https://github.com/AuroraInteractive/network-script-data/tree/master/denizen_scripts/survival/repo-link/global_systems/drop_tables.dsc#L84)

This need to:
- run only if MythicMob dies (dont use that event, though)
- drop from the drop table based on the MythicMob's level

**Comment by BehrRiley** [comment]
`<script[drop_table_data].list_keys[mob_level.]` would be invalid; that last dot either doesn't belong or the path needs corrected

**Comment by Ph4i1ur3** [comment]
That's a byproduct of the `mob_level` not being set properly
