### ISSUE TITLE
[BORKED] Meseeks is f&%$ed

### ISSUE THREAD

**Issue by Ph4i1ur3** [Adriftus-Studios/network-script-data#63]
> **Error Message**:
`Tag <player.flag[Behrry.Interaction.ActiveNPC]> is invalid!`

> **Script Information**:
Script Name:  `npc_interaction`
Script Reference:  [`survival/./repo-link/meeseeks_shit/NPC Supplements.dsc`](https://github.com/AuroraInteractive/network-script-data/tree/master/denizen_scripts/survival/repo-link/meeseeks_shit/NPC Supplements.dsc#L55)

**Comment by BehrRiley** [comment]
This script needs removed, it's deprecated in favor of it's re-write on my local. Closing until re-opening as an available priority script for the server/network
