### ISSUE TITLE
[BORK] Claims spam when you are entering a different chunk in the same claim.

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#64]
We don't need to see a message when we are entering a different chunk without leaving a claim.

> **How To Reproduce**:
Go to a claim
go to a chunk in the same claim

> **Expected behavior**:
not being spammed to hell.

> **Screenshots**:
![image](https://user-images.githubusercontent.com/25861695/90506816-b5d7de80-e109-11ea-8202-79c7edbfa173.png)
![image](https://user-images.githubusercontent.com/25861695/90506925-e15ac900-e109-11ea-940f-a59a589a6196.png)
![image](https://user-images.githubusercontent.com/25861695/90506960-ecadf480-e109-11ea-81fc-c8b1169aa066.png)

**Comment by Ph4i1ur3** [comment]
Fixed.
