### ISSUE TITLE
[BORK] Particles in spawn seem to by off by +1Y

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#66]
> **Describe the bug**:

![image](https://user-images.githubusercontent.com/25861695/90507253-71990e00-e10a-11ea-97fd-6b2b4a7c8bd0.png)
The cosmetic shop and spawn particles seem to be shifted 1 up from where they should be.

> **How To Reproduce**:

/spawn

> **Expected behavior**:
Particles falling to ground, and cosmetic shop particles not obscuring the vendor.

> **Screenshots**:
![image](https://user-images.githubusercontent.com/25861695/90507337-97beae00-e10a-11ea-95ca-3af3b7243623.png)

![image](https://user-images.githubusercontent.com/25861695/90507359-a1481600-e10a-11ea-84c8-e54895d17fe6.png)

> **Additional context**:
Soul forge particles still look ok.

**Comment by Ph4i1ur3** [comment]
Fixed.
