### ISSUE TITLE
[BORK] Hub1 is a dangerous place

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#68]
> **Describe the bug**:
The safety scripts haven't made their way to the hub world yet.

> **How To Reproduce**:
just try and kill yourself in hub 

> **Expected behavior**:
damage events cancelled.

> **Screenshots**:

![image](https://user-images.githubusercontent.com/25861695/90507849-6eeae880-e10b-11ea-8dd1-f2c4a554c326.png)

> **Additional context**:
Marked as done in #24 but not actually completed.

**Comment by BehrRiley** [comment]
These systems are written and completed, they just need copied from `Survival`.
