### ISSUE TITLE
In game Nick to Discord

### ISSUE THREAD

**Issue by Mutim** [Adriftus-Studios/network-script-data#70]
Currently, when chatting from in-game, your message is sent to discord. (duhh)

My feature request is to parse the character nickname, in the discord message that's sent. 

This could be in a number of ways. 

How other plugins do nicknames, with a *<nickname> (Notice the asterisk in front, so you know it's a nick)

 - or - 

Simply just write their nickname as the bots name impersonating the player for the message. 

Any clarification needed, I can give. 
![image](https://user-images.githubusercontent.com/22847483/90553329-d16ad580-e159-11ea-97f0-2b51310fe335.png)

In this image, say Berufeng's name was "Bill" in game via nickname. This should be presented in the chat that way. =)

**Comment by pjochillin** [comment]
This should be fixed with [https://github.com/BehrRiley/network-script-data/pull/36](url), where Discord messages now have the player's display name (and will use the default username if n/a).

**Comment by pjochillin** [comment]
Also fixed the avatar URL when sending discord messages with [https://github.com/BehrRiley/network-script-data/pull/37](url), where messages now have the correct picture.
