### ISSUE TITLE
(Feature Request) Anti-AFK script in hub

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#81]
> **The Type of request**:

One off script

> **Who is requesting this**:

Eutherin

> **Describe the feature**:

Kick AFK players in hub to free up space.

> **Describe the impact**: 

_performance_

> **Describe the reach of this feature**:

Basically just need it for hub for now

> **Describe the cost of not doing this request**: 

_muh performance_

> **Describe which goals this helps**: 

_performaaaaancceeee_

> **Describe the evidence that you have on the need for this request**: 

SkeletalAM was afk in hub for like 24 hours

> **Describe if you have any ideas on how we may solve this**: 

Check the time since their last movement or something.

> **Describe how urgent this is and why**: 

SkeletalAM was afk in hub for like 24 hours if this is unchecked it will be a problem when we launch

**Comment by pjochillin** [comment]
This feature request was added in [https://github.com/BehrRiley/network-script-data/pull/52](url). Does it work correctly and function as intended?
