### ISSUE TITLE
Parkour Cuboids need created

### ISSUE THREAD

**Issue by Grumblin** [Adriftus-Studios/network-script-data#90]
Bird is mean and doesn't let me start parkour, so I cannot play the jumpy jump game.

It's missing a notable cuboid that lets you start the game

**Comment by BehrRiley** [comment]
This script is not broken, there are no noted cuboids evident for the script to run.

Script in reference is [spawn_parkour.dsc](https://github.com/Adriftus-Studios/network-script-data/blob/e9d7d0d30b3f7b5cd4c8d230e8cc03ccacac83d8/denizen_scripts/survival/repo-link/spawn_scripts/spawn_parkour.dsc).

**Comment by Eutherin** [comment]
Should these be created using `/ex note <cuboid[coordinates]> as:parkour<level>` where <level> is replaced with the number?

![image](https://user-images.githubusercontent.com/25861695/97156635-38959f00-1734-11eb-8964-0e5346922432.png)

**Comment by Eutherin** [comment]
created parkour0-4
0/1 right here between chests, wasnt sure which one the script needed
![image](https://user-images.githubusercontent.com/25861695/97159114-9bd50080-1737-11eb-8076-0888b1808d8f.png)
2 goes from the leftmost top slab to the fence
![image](https://user-images.githubusercontent.com/25861695/97159262-d343ad00-1737-11eb-8ba2-0a576ea434a8.png)
3 goes from fence to fence
![image](https://user-images.githubusercontent.com/25861695/97159309-e5255000-1737-11eb-9f7e-901de7418e99.png)
4 goes from this fencepost on center to the block below the fenceposts across the center of the platform.
![image](https://user-images.githubusercontent.com/25861695/97159354-f8d0b680-1737-11eb-9cf9-9dc781f6ab80.png)
Coordinates:
![image](https://user-images.githubusercontent.com/25861695/97159376-fff7c480-1737-11eb-8df4-b8c5dff72bdc.png)

**Comment by Eutherin** [comment]
Finished as part of weekly patch.
