### ISSUE TITLE
[BORK] You can apply leads to animals you can't kill in others claims

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#96]
> **Describe the bug**:
You can apply leads to animals you can't kill in others claims

> **How To Reproduce**:
Take lead, right click on animal

> **Expected behavior**:
Lead usage should be blocked.

> **Additional context**:
This allows you to steal animals from players claims to kill or mount them where otherwise you would not be able to do that.

**Comment by Ph4i1ur3** [comment]
Resolved by #103
