### ISSUE TITLE
[BORK] Souls can be cooked

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#97]
> **Describe the bug**:

Souls can be cooked into bricks when placed in a furnace

> **How To Reproduce**:

Example:
SMELT A SOUL MUAHAHHAHAHA

> **Expected behavior**:
It should appear like the item cannot be smelted.

> **Screenshots**:

![](https://cdn.discordapp.com/attachments/626080540638052382/755333587431194654/unknown.png)

![](https://cdn.discordapp.com/attachments/626080540638052382/755333602148876329/unknown.png)

> **Additional context**:
Maybe we can make souls a different item thats not smeltable by default? A clay ball for a soul is pretty lame anyway, we should use the soul particle like under the soul forge IMO.

**Comment by Ph4i1ur3** [comment]
Resolved by #103
