### ISSUE TITLE
[BORK] Silverfish can break blocks in claims

### ISSUE THREAD

**Issue by Eutherin** [Adriftus-Studios/network-script-data#99]
You can drag a silverfish to a claim then let it infest a block, then use that to break a block you couldnt normally break.

**Example:**
1. find silverfish
2. drag to claim
3. let it infest a block
4. trigger it being hostile

**Expected behavior**:
should not let silverfish infest blocks, or should not let them re-emerge

**Screenshots**:

![image](https://user-images.githubusercontent.com/25861695/93190486-4816d680-f6f8-11ea-9ced-a8667ce2e7da.png)

![image](https://user-images.githubusercontent.com/25861695/93190519-549b2f00-f6f8-11ea-885b-a5f62d1998f0.png)

**Comment by Eutherin** [comment]
If you repeat it enough you can REALLY do some damage hehe
![image](https://user-images.githubusercontent.com/25861695/93191002-e0ad5680-f6f8-11ea-8080-f0b82ff96ba9.png)

**Comment by Ph4i1ur3** [comment]
Resolved by #103
